package:
  name: hicplot
  version: 1.0.3

source:
  url: https://files.pythonhosted.org/packages/cc/21/617eb780bfe8a02b04f2191836597aa3a8f57f1c5a1ef531ae427f9a0f9e/hicplot-1.0.3.tar.gz
  md5: f14b4cfd775cf3c32f14547da6bfa5eb

build:
  number: 0

requirements:
  build:
    - python >=3.12
    - setuptools
  run:
    - python >=3.12
    - numpy =1.26.4
    - pandas ==1.4.3
    - matplotlib
    - pyBigWig
    - pyranges ==0.0.117
    - cooler

about:
  home: https://github.com/BenxiaHu/HiCPlot
  license: MIT
  summary: "How to run HiCPlot to plot heatmaps."
  description: "How to run HiCPlot to plot heatmaps."
  dev_url: https://github.com/BenxiaHu/HiCPlot

