package:
  name: hicplot
  version: 1.51

source:
  url: https://files.pythonhosted.org/packages/b0/93/39db2e3ad09f60e098e507611379fdb6cee0781dbb7f1a0be9247c7411af/hicplot-1.5.1.tar.gz
  md5: 9e38a9ccc0c878dd578b36703b047bd0

build:
  number: 0

requirements:
  build:
    - python =3.12
    - numpy =1.26.4
    - cython
    - setuptools
    - pip
  run:
    - python =3.12
    - numpy =1.26.4
    - pandas =1.4.3
    - matplotlib
    - pyBigWig
    - pyranges =0.0.117
    - cooler =0.10.2

about:
  home: https://github.com/BenxiaHu/HiCPlot
  license: MIT
  summary: "How to run HiCPlot to plot heatmaps."
  description: "How to run HiCPlot to plot heatmaps."
  dev_url: https://github.com/BenxiaHu/HiCPlot

