package:
  name: hicplot
  version: 1.0.5

source:
  url: https://files.pythonhosted.org/packages/f1/22/d754cda73920af8396981bf20dff356fa2652e96da4b246dd60b8d6de9b5/hicplot-1.0.4.tar.gz
  md5: f14b4cfd775cf3c32f14547da6bfa5eb

build:
  number: 0

requirements:
  build:
    - python >=3.12
    - setuptools
  run:
    - python >=3.12
    - numpy =1.26.4
    - pandas ==1.4.3
    - matplotlib
    - pyBigWig
    - pyranges ==0.0.117
    - cooler

about:
  home: https://github.com/BenxiaHu/HiCPlot
  license: MIT
  summary: "How to run HiCPlot to plot heatmaps."
  description: "How to run HiCPlot to plot heatmaps."
  dev_url: https://github.com/BenxiaHu/HiCPlot

