package:
  name: hicplot
  version: 1.50

source:
  url: https://files.pythonhosted.org/packages/ff/5d/56b541dfb3cd046d782ec386637de24a2bda219e3149c1447ade1f3aa8e3/hicplot-1.5.0.tar.gz
  md5: 6e968c4067b2cb3770285e672cba196e

build:
  number: 0

requirements:
  build:
    - python =3.12
    - numpy =1.26.4
    - cython
    - setuptools
    - pip
  run:
    - python =3.12
    - numpy =1.26.4
    - pandas =1.4.3
    - matplotlib
    - pyBigWig
    - pyranges =0.0.117
    - cooler =0.10.2

about:
  home: https://github.com/BenxiaHu/HiCPlot
  license: MIT
  summary: "How to run HiCPlot to plot heatmaps."
  description: "How to run HiCPlot to plot heatmaps."
  dev_url: https://github.com/BenxiaHu/HiCPlot

